### ISSUE TITLE
white noise appears *randomly* in files after processing

### ISSUE THREAD

**Issue by drakpo** [piscue/audio-randomizer#5]
files processed approx 75% of the time include white noise. cannot reproduce this consistently. MacOSX 10.13 and Debian 9. any pointers to a resolution of this gratefully received.  Python 3.9.13

**Comment by piscue** [comment]
I managed to reproduce the issue, I try to take a look at how to fix it, but any help is welcomed

**Comment by drakpo** [comment]
the only thing I can see that MIGHT be happening is that the white noise generator (which I see is in the code) is getting triggered, but I cannot trace *how* that might be happening. possibly too obvious?

**Comment by piscue** [comment]
> the only thing I can see that MIGHT be happening is that the white noise generator (which I see is in the code) is getting triggered, but I cannot trace _how_ that might be happening. possibly too obvious?

Can you point to the line you see the white noise generator?

**Comment by drakpo** [comment]
it was in one of the modules, but I can't find it now. sorry - was a while ago now. will go back to my notes and get back to you. the other thing I THOUGHT might be the problem was memory, but that now doesn't seem to be the case. as I said, what was also odd is that it wasn't consistent.

**Comment by piscue** [comment]
I just fixed the issue, if run python directly it shouldn't happen. If you use docker, I still have to update the image

**Comment by piscue** [comment]
I see, this is unrelated to the white noise but indeed appeared with the fix. I would suggest to close this issue and create a new one
