### ISSUE TITLE
"... -s 256" fails.

### ISSUE THREAD

**Issue by drakpo** [piscue/audio-randomizer#7]
-s 128 and lower values work, but...

python3 main.py -i RESULTS/b.wav -s 256
Traceback (most recent call last):
  File "/Users/AAA/Downloads/SOUND/audio-randomizer-master/main.py", line 98, in <module>
    wavedict = load_wave(vars.input, int(vars.splits))
  File "/Users/AAA/Downloads/SOUND/audio-randomizer-master/main.py", line 64, in load_wave
    wavedict['frames'] = split_frames(wavefile, splits, wavedict['duration'])
  File "/Users/AAA/Downloads/SOUND/audio-randomizer-master/main.py", line 50, in split_frames
    wavefile.setpos(int(frame_position))
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/wave.py", line 229, in setpos
    raise Error('position not in range')
wave.Error: position not in range

**Comment by piscue** [comment]
I see the point and I would love to understand the use case. You wanna really create a very randomized file? Could you explain a bit? 

For now I can capture the exception and print a better message

**Comment by piscue** [comment]
With the latest merge, you should be able to increase the number of the splits as much as you want, in decrease of skipping the lasts splits on the file, creating a "slightly" smaller output file

**Comment by drakpo** [comment]
that is exactly what I want to do. was doing this with PyDub's AudioSegment, but was wanting to see if your version, without the library, could do it. will try this version.

**Comment by piscue** [comment]
with this version I can also increase a lot the number of splits `131072`, increasing the waiting time for the output, and create a very interesting "noise" with a very scrambled file

```shell
docker run -v ~/Downloads:/wav piscue/audio-randomizer -i /wav/test_randomizer.wav -s 131072
```

**Comment by drakpo** [comment]
all works here, now, thank you.
